import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar"
import { ThemeSwitcher } from "@/components/ThemeSwitcher"
import { Footer } from "@/components/Footer"



export const metadata: Metadata = {
  title: "Dallon Gunn's Portfolio",
  description: "Generated by me",
  icons: {
    icon: {
      url: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🌊</text></svg>",
      type: "image/svg+xml",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="nord" lang="en">
      <body>
        <NavBar></NavBar>
        <main className="p-6 min-h-screen">
          {children}
        </main>
        <Footer></Footer>
        <ThemeSwitcher></ThemeSwitcher>
      </body>
    </html>
  );
}
